
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-project-config
data:
  APPLICATION_PROFILE: test
  LOGGING_LEVEL: INFO
---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-project-secret
type: Opaque
data:
  USERNAME: QW5kZXJzb25FbGl0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-project
  template:
    metadata:
      labels:
        app: kubernetes-project
    spec:
      containers:
        - name: kubernetes-project
          image: andersonelit/kubernetesproject:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: kubernetes-project-config
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: kubernetes-project-secret
                  key: USERNAME
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL-USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL-PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-project-service
spec:
  selector:
    app: kubernetes-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer