apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-project
  template:
    metadata:
      labels:
        app: kubernetes-project
    spec:
      containers:
        - name: kubernetes-project
          image: andersonelit/kubernetesproject:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-project-service
spec:
  selector:
    app: kubernetes-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer